---
- name: Setting up aggregate list
  set_fact:
    all_aggregates: []
- name: Setting up non-root aggregate list
  set_fact:
    aggregate_list: []
- name: Get aggregate info
  netapp.ontap.na_ontap_info: 
    state: info
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    gather_subset: "aggregate_info"
  register: ontap_info
- name: output more info
  debug:
    var: ontap_info.ontap_info
- name: Get aggregates
  set_fact:
    all_aggregates: "{{ all_aggregates + [ item.key ] }}"
  loop: "{{ ontap_info.ontap_info.aggregate_info | dict2items }}"
- name: output more info
  debug:
    var: all_aggregates
- name: loop to find non-root aggrs
  set_fact:
    aggregate_list: "{{ aggregate_list + [ item ] }}"
  loop: "{{ all_aggregates }}"
  when: ontap_info.ontap_info.aggregate_info[ item ].aggr_raid_attributes.is_root_aggregate == "false"
- name: output more info
  debug:
    var: aggregate_list
