---
- name: Edit namespaces
  netapp.ontap.na_ontap_nvme_namespace:
    state: "{{ state }}"
    block_size: "{{ item.block_size }}"
    path: "{{ item.path }}"
    vserver: "{{ item.vserver }}"
    size: "{{ item.size }}"
    ostype: "{{ item.ostype }}"
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"

  connection: local
